In [1]:
import numpy as np

In [2]:
# Create a list w/ 9 elements
#list = range(8)
list = ([0,1,2,3,4,5,6,7,8])
list

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
# convert list to 3x3 NumPy array
matrix_3x3 = np.array(list).reshape(3,3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# M A X

In [91]:
# Find max element in rows
matrix_3x3_row_max = np.max(matrix_3x3, axis=0)
matrix_3x3_row_max

array([6, 7, 8])

In [92]:
# Find max element in columns
matrix_3x3_column_max = np.max(matrix_3x3, axis=1)
matrix_3x3_column_max

array([2, 5, 8])

In [4]:
# max element
max_element = np.max(matrix_3x3)
max_element

8

# M I N

In [94]:
# Find min element in rows
matrix_3x3_row_min = np.min(matrix_3x3, axis=0)
matrix_3x3_row_min

array([0, 1, 2])

In [95]:
# Find min element in column
matrix_3x3_column_min = np.min(matrix_3x3, axis=1)
matrix_3x3_column_min

array([0, 3, 6])

In [5]:
# min element
min_element = np.min(matrix_3x3)
min_element

0

# S U M

In [6]:
# sum of the columns in a 3x3 matrix to a 1x3 matrix
col1_sum_matrix = matrix_3x3[0,0] + matrix_3x3[0,1] + matrix_3x3[0,2]
col2_sum_matrix = matrix_3x3[1,0] + matrix_3x3[1,1] + matrix_3x3[1,2]
col3_sum_matrix = matrix_3x3[2,0] + matrix_3x3[2,1] + matrix_3x3[2,2]

col_sum_matrix = np.array([col1_sum_matrix, col2_sum_matrix,col3_sum_matrix])

col_sum_matrix

array([ 3, 12, 21])

In [7]:
# sum of the rows in a 3x3 matrix to a 1x3 matrix
row1_sum_matrix = matrix_3x3[0][0] + matrix_3x3[0][1] + matrix_3x3[0][2]
row2_sum_matrix = matrix_3x3[1][0] + matrix_3x3[1][1] + matrix_3x3[1][2]
row3_sum_matrix = matrix_3x3[2][0] + matrix_3x3[2][1] + matrix_3x3[2][2]

rows_sum_matrix = np.array([row1_sum_matrix,
                            row2_sum_matrix,
                            row3_sum_matrix])

rows_sum_matrix

array([ 3, 12, 21])

In [8]:
element_sum = np.sum(matrix_3x3)
element_sum

36

In [114]:
row_sum_matrix = np.sum(matrix_3x3, axis=0)
row_sum_matrix

array([ 9, 12, 15])

In [113]:
# alternate sum that is simplier

col_sum_matrix = np.sum(matrix_3x3, axis=1)
col_sum_matrix

array([ 3, 12, 21])

In [11]:
matrix_3x3[0,:]

array([0, 1, 2])

In [12]:
matrix_3x3[:,0]

array([0, 3, 6])

In [13]:
len(matrix_3x3[:,0])

3

In [14]:
# Find the mean
col1_mean_matrix = (matrix_3x3[0,0] + matrix_3x3[1,0] + matrix_3x3[2,0]  ) / len(matrix_3x3[:,0])
col1_mean_matrix

#col_mean_matrix

3.0

In [15]:
# Find the mean
row1_mean_matrix = (matrix_3x3[0,1] + matrix_3x3[1,1] + matrix_3x3[2,1]  ) / len(matrix_3x3[:,1])
row1_mean_matrix

4.0

In [16]:
# Find the mean
col1_mean_matrix = (matrix_3x3[0,2] + matrix_3x3[1,2] + matrix_3x3[2,2]  ) / len(matrix_3x3[:,2])
col1_mean_matrix

5.0

In [17]:
# Find the mean
row_of_column_means = np.sum(matrix_3x3, axis=0 ) / len(matrix_3x3[:,0])
row_of_column_means

array([3., 4., 5.])

In [18]:
column_of_row_means = np.sum(matrix_3x3, axis=1 ) / len(matrix_3x3[0,:])
column_of_row_means

array([1., 4., 7.])

In [19]:
mean_matrix_3x3 = np.mean(matrix_3x3)
mean_matrix_3x3

4.0

In [20]:
#other_col1_mean_matrix[0]

In [21]:
matrix_3x3[0,:]

array([0, 1, 2])

## VARIANCE: Row 1

In [22]:
# Find all the (element - mean) in row 1

row1_element_minus_mean = matrix_3x3[0,:] - column_of_row_means[0]
row1_element_minus_mean

array([-1.,  0.,  1.])

In [23]:
# Find all the individual variances row 1

row1_individual_variances = (row1_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3[0,:]))
row1_individual_variances

array([0.33333333, 0.        , 0.33333333])

In [82]:
# Find the variance for row1 using the sumation

row1_variance = np.sum(row1_individual_variances)
row1_variance

0.6666666666666666

In [81]:
# Find the variance
# [(element - mean)^2] / num of elements

((matrix_3x3[0,0] - mean_matrix_3x3)**2) / len(matrix_3x3)

5.333333333333333

## VARIANCE: Row 2

In [26]:
# Find all the (element - mean) in row 2

row2_element_minus_mean = matrix_3x3[1,:] - column_of_row_means[1]
row2_element_minus_mean

array([-1.,  0.,  1.])

In [27]:
# Find all the individual variances row 2

row2_individual_variances = (row2_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3[1,:]))
row2_individual_variances

array([0.33333333, 0.        , 0.33333333])

In [28]:
# Find the variance for row2 using the sumation

row2_variance = np.sum(row2_individual_variances)
row2_variance

0.6666666666666666

## VARIANCE: Row 3

In [29]:
# Find all the (element - mean) in row 3

row3_element_minus_mean = matrix_3x3[2,:] - column_of_row_means[2]
row3_element_minus_mean

array([-1.,  0.,  1.])

In [30]:
# Find all the individual variances row 3

row3_individual_variances = (row3_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3[2,:]))
row3_individual_variances

array([0.33333333, 0.        , 0.33333333])

In [31]:
# Find the variance for row3 using the sumation

row3_variance = np.sum(row3_individual_variances)
row3_variance

0.6666666666666666

In [32]:
column_variances = [row1_variance, row2_variance, row3_variance]
column_variances

[0.6666666666666666, 0.6666666666666666, 0.6666666666666666]

## VARIANCE: Column 1

In [33]:
# Find all the (element - mean) in column 1

col1_element_minus_mean = matrix_3x3[:,0] - row_of_column_means[0]
col1_element_minus_mean

array([-3.,  0.,  3.])

In [34]:
np.count_nonzero(~np.isnan(matrix_3x3[:,0]))

3

In [35]:
# Find all the individual variances column 1

col1_individual_variances = (col1_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3[:,0]))
col1_individual_variances

array([3., 0., 3.])

In [36]:
# Find the variance for column 1 using the sumation

col1_variance = np.sum(col1_individual_variances)
col1_variance

6.0

## VARIANCE: Column 2

In [37]:
# Find all the (element - mean) in column 2

col2_element_minus_mean = matrix_3x3[:,1] - row_of_column_means[1]
col2_element_minus_mean

array([-3.,  0.,  3.])

In [38]:
np.count_nonzero(~np.isnan(matrix_3x3[:,1]))

3

In [39]:
# Find all the individual variances column 2

col2_individual_variances = (col2_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3[:,1]))
col2_individual_variances

array([3., 0., 3.])

In [40]:
# Find the variance for column 2 using the sumation

col2_variance = np.sum(col2_individual_variances)
col2_variance

6.0

## VARIANCE: Column 3

In [41]:
# Find all the (element - mean) in column 3

col3_element_minus_mean = matrix_3x3[:,2] - row_of_column_means[2]
col3_element_minus_mean

array([-3.,  0.,  3.])

In [42]:
# Find all the individual variances column 3

col3_individual_variances = (col3_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3[:,2]))
col3_individual_variances

array([3., 0., 3.])

In [43]:
# Find the variance for column 3 using the sumation

col3_variance = np.sum(col3_individual_variances)
col3_variance

6.0

In [44]:
row_variances = [col1_variance, col2_variance, col3_variance]

## VARIANCE: Entire Matrix

In [45]:
# Find all the (element - mean) in enitre matrix

matrix_element_minus_mean = matrix_3x3[:,:] - mean_matrix_3x3
matrix_element_minus_mean

array([[-4., -3., -2.],
       [-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

In [46]:
np.count_nonzero(~np.isnan(matrix_3x3))

9

In [47]:
# Find all the individual variances in enitre matrix

matrix_individual_variances = (matrix_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3))
matrix_individual_variances

array([[1.77777778, 1.        , 0.44444444],
       [0.11111111, 0.        , 0.11111111],
       [0.44444444, 1.        , 1.77777778]])

In [48]:
# Find the variance for the enitre matrix using the sumation

matrix_variance = np.sum(matrix_individual_variances)
matrix_variance

6.666666666666666

In [49]:
len(matrix_3x3[:,:])

3

In [50]:
variances = [row_variances, column_variances, matrix_variance]
variances

[[6.0, 6.0, 6.0],
 [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
 6.666666666666666]

# STANDARD DEVIATION

## Find Std Dev of Rows

In [51]:
row_variances

[6.0, 6.0, 6.0]

In [52]:
std_dev_row = np.sqrt(row_variances)
std_dev_row

array([2.44948974, 2.44948974, 2.44948974])

## Find Std Dev of Columns

In [53]:
column_variances

[0.6666666666666666, 0.6666666666666666, 0.6666666666666666]

In [54]:
std_dev_column = np.sqrt(column_variances)
std_dev_column

array([0.81649658, 0.81649658, 0.81649658])

## Find Std Dev of Entire Matrix

In [55]:
matrix_variance

6.666666666666666

In [56]:
std_dev_entire_matrix = np.sqrt(matrix_variance)
std_dev_entire_matrix

2.581988897471611

# Combine all Std Devs

In [57]:
std_devs = [std_dev_row, std_dev_column, std_dev_entire_matrix]
std_devs

[array([2.44948974, 2.44948974, 2.44948974]),
 array([0.81649658, 0.81649658, 0.81649658]),
 2.581988897471611]

# Convert all matrices and etc into a Dictionary

## Convert Maxes to a List

In [98]:
matrix_3x3_row_max_list = matrix_3x3_row_max.tolist()
matrix_3x3_row_max_list

[6, 7, 8]

In [102]:
matrix_3x3_column_max_list = matrix_3x3_column_max.tolist()
matrix_3x3_column_max_list

[2, 5, 8]

In [103]:
type(max_element)

numpy.int32

In [107]:
max_element_list = max_element.tolist()
max_element_list

8

In [119]:
max_list = [matrix_3x3_row_max_list, matrix_3x3_column_max_list, max_element_list]
max_list

[[6, 7, 8], [2, 5, 8], 8]

## Convert Mins to a List

In [108]:
matrix_3x3_row_min_list = matrix_3x3_row_min.tolist()

In [109]:
matrix_3x3_column_min_list = matrix_3x3_column_min.tolist()

In [110]:
min_element_list = min_element.tolist()

In [121]:
min_list = [matrix_3x3_row_min_list, matrix_3x3_column_min_list, min_element_list]
min_list

[[0, 1, 2], [0, 3, 6], 0]

## Convert Sums to a List

In [131]:
row_sum_matrix

array([ 9, 12, 15])

In [116]:
row_sum_matrix_list = row_sum_matrix.tolist()

In [109]:
matrix_3x3_column_min_list = matrix_3x3_column_min.tolist()

In [110]:
min_element_list = min_element.tolist()

In [122]:
sum_list = [row_sum_matrix_list, matrix_3x3_column_min_list, min_element_list]
sum_list

[[9, 12, 15], [0, 3, 6], 0]

## Convert Means to a List

In [77]:
row_of_column_means_list = row_of_column_means.tolist()
row_of_column_means_list

[3.0, 4.0, 5.0]

In [76]:
column_of_row_means_list = column_of_row_means.tolist()
column_of_row_means_list

[1.0, 4.0, 7.0]

In [80]:
mean_matrix_3x3_list = mean_matrix_3x3.tolist()
mean_matrix_3x3_list

4.0

In [124]:
mean_list = [row_of_column_means_list, column_of_row_means_list, mean_matrix_3x3_list]
mean_list

[[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0]

## Convert Variances to a List

In [87]:
type(row_variances)

list

In [88]:
type(column_variances)

list

In [89]:
type(variances)

list

## Convert STD Devs to a List

In [58]:
# Convert elements inside std_devs_row to a list
std_dev_row_list = std_dev_row.tolist()
std_dev_row_list

[2.449489742783178, 2.449489742783178, 2.449489742783178]

In [61]:
# Convert elements inside std_devs_column to a list
std_dev_column_list = std_dev_column.tolist()
std_dev_column_list

[0.816496580927726, 0.816496580927726, 0.816496580927726]

In [63]:
# Convert elements inside std_devs_column to a list
std_dev_entire_matrix_list = std_dev_entire_matrix.tolist()
std_dev_entire_matrix_list

2.581988897471611

In [117]:
std_dev_lists = [std_dev_row_list, std_dev_column_list, std_dev_entire_matrix_list]
std_dev_lists

[[2.449489742783178, 2.449489742783178, 2.449489742783178],
 [0.816496580927726, 0.816496580927726, 0.816496580927726],
 2.581988897471611]

In [59]:
# Convert elements inside std_dev_row to a dictionary w/ an index starting at 1
std_dev_dict = dict(enumerate(std_dev_row.flatten(), 1))
std_dev_dict

{1: 2.449489742783178, 2: 2.449489742783178, 3: 2.449489742783178}

In [60]:
# dict({'standard deviation': [std_devs[0],std_devs[1],std_devs[2]]})
dict({'standard deviation': std_devs[0:3]})

{'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]),
  array([0.81649658, 0.81649658, 0.81649658]),
  2.581988897471611]}

## Convert One Large List

In [125]:
calculations_list = [mean_list, variances, std_dev_lists, max_list, min_list, sum_list]
calculations_list

[[[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666666],
 [[2.449489742783178, 2.449489742783178, 2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 [[6, 7, 8], [2, 5, 8], 8],
 [[0, 1, 2], [0, 3, 6], 0],
 [[9, 12, 15], [0, 3, 6], 0]]

## Create One Large Dictionary

In [130]:
calculations = dict({'mean':mean_list,
                     'variance':variances,
                     'standard deviation':std_dev_lists,
                     'max':max_list,
                     'min':min_list,
                     'sum':sum_list})
calculations

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666666],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [0, 3, 6], 0]}