In [1]:
import numpy as np

In [2]:
# Create a list w/ 9 elements
#list = range(8)
list = ([0,1,2,3,4,5,6,7,8])
list

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
# convert list to 3x3 NumPy array
matrix_3x3 = np.array(list).reshape(3,3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# max element
max_element = np.max(matrix_3x3)
max_element

8

In [7]:
# min element
min_element = np.min(matrix_3x3)
min_element

0

In [8]:
# sum of the columns in a 3x3 matrix to a 1x3 matrix
col1_sum_matrix = matrix_3x3[0,0] + matrix_3x3[0,1] + matrix_3x3[0,2]
col2_sum_matrix = matrix_3x3[1,0] + matrix_3x3[1,1] + matrix_3x3[1,2]
col3_sum_matrix = matrix_3x3[2,0] + matrix_3x3[2,1] + matrix_3x3[2,2]

col_sum_matrix = np.array([col1_sum_matrix, col2_sum_matrix,col3_sum_matrix])

col_sum_matrix

array([ 3, 12, 21])

In [9]:
# sum of the rows in a 3x3 matrix to a 1x3 matrix
row1_sum_matrix = matrix_3x3[0][0] + matrix_3x3[0][1] + matrix_3x3[0][2]
row2_sum_matrix = matrix_3x3[1][0] + matrix_3x3[1][1] + matrix_3x3[1][2]
row3_sum_matrix = matrix_3x3[2][0] + matrix_3x3[2][1] + matrix_3x3[2][2]

rows_sum_matrix = np.array([row1_sum_matrix,
                            row2_sum_matrix,
                            row3_sum_matrix])

rows_sum_matrix

array([ 3, 12, 21])

In [11]:
element_sum = np.sum(matrix_3x3)
element_sum

36

In [31]:
other_row_sum_matrix = np.sum(matrix_3x3, axis=0)
other_row_sum_matrix

array([ 9, 12, 15])

In [30]:
# alternate sum that is simplier

other_col_sum_matrix = np.sum(matrix_3x3, axis=1)
other_col_sum_matrix

array([ 3, 12, 21])

In [15]:
matrix_3x3[0,:]

array([0, 1, 2])

In [13]:
matrix_3x3[:,0]

array([0, 3, 6])

In [14]:
len(matrix_3x3[:,0])

3

In [47]:
# Find the mean
col1_mean_matrix = (matrix_3x3[0,0] + matrix_3x3[1,0] + matrix_3x3[2,0]  ) / len(matrix_3x3[:,0])
col1_mean_matrix

#col_mean_matrix

3.0

In [49]:
# Find the mean
row1_mean_matrix = (matrix_3x3[0,1] + matrix_3x3[1,1] + matrix_3x3[2,1]  ) / len(matrix_3x3[:,1])
row1_mean_matrix

4.0

In [20]:
# Find the mean
col1_mean_matrix = (matrix_3x3[0,2] + matrix_3x3[1,2] + matrix_3x3[2,2]  ) / len(matrix_3x3[:,2])
col1_mean_matrix

5.0

In [23]:
# Find the mean
other_col1_mean_matrix = np.sum(matrix_3x3, axis=0 ) / len(matrix_3x3[:,0])
other_col1_mean_matrix

array([3., 4., 5.])

In [25]:
column_of_row_means = np.sum(matrix_3x3, axis=1 ) / len(matrix_3x3[0,:])
column_of_row_means

array([1., 4., 7.])

In [28]:
mean_matrix_3x3 = np.mean(matrix_3x3)
mean_matrix_3x3

4.0

In [39]:
other_col1_mean_matrix[0]

3.0

In [45]:
matrix_3x3[0,:]

array([0, 1, 2])

In [60]:
# Find all the (element - mean) in row 1

row1_element_minus_mean = matrix_3x3[0,:] - 1
row1_element_minus_mean

array([-1,  0,  1])

In [61]:
# Find all the individual variances row 1

row1_individual_variances = (row1_element_minus_mean**2) / 3
row1_individual_variances

array([0.33333333, 0.        , 0.33333333])

In [63]:
# Find the variance for row1 using the sumation

row1_variance = np.sum(row1_individual_variances)
row1_variance

0.6666666666666666

In [34]:
# Find the variance
# [(element - mean)^2] / num of elements

((matrix_3x3[0,0] - mean_matrix_3x3)**2) / len(matrix_3x3)


5.333333333333333