In [46]:
import numpy as np

In [47]:
# Create a list w/ 9 elements
#list = range(8)
list = ([0,1,2,3,4,5,6,7,8])
list

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [48]:
# convert list to 3x3 NumPy array
matrix_3x3 = np.array(list).reshape(3,3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
# max element
max_element = np.max(matrix_3x3)
max_element

8

In [50]:
# min element
min_element = np.min(matrix_3x3)
min_element

0

In [51]:
# sum of the columns in a 3x3 matrix to a 1x3 matrix
col1_sum_matrix = matrix_3x3[0,0] + matrix_3x3[0,1] + matrix_3x3[0,2]
col2_sum_matrix = matrix_3x3[1,0] + matrix_3x3[1,1] + matrix_3x3[1,2]
col3_sum_matrix = matrix_3x3[2,0] + matrix_3x3[2,1] + matrix_3x3[2,2]

col_sum_matrix = np.array([col1_sum_matrix, col2_sum_matrix,col3_sum_matrix])

col_sum_matrix

array([ 3, 12, 21])

In [52]:
# sum of the rows in a 3x3 matrix to a 1x3 matrix
row1_sum_matrix = matrix_3x3[0][0] + matrix_3x3[0][1] + matrix_3x3[0][2]
row2_sum_matrix = matrix_3x3[1][0] + matrix_3x3[1][1] + matrix_3x3[1][2]
row3_sum_matrix = matrix_3x3[2][0] + matrix_3x3[2][1] + matrix_3x3[2][2]

rows_sum_matrix = np.array([row1_sum_matrix,
                            row2_sum_matrix,
                            row3_sum_matrix])

rows_sum_matrix

array([ 3, 12, 21])

In [53]:
element_sum = np.sum(matrix_3x3)
element_sum

36

In [54]:
other_row_sum_matrix = np.sum(matrix_3x3, axis=0)
other_row_sum_matrix

array([ 9, 12, 15])

In [55]:
# alternate sum that is simplier

other_col_sum_matrix = np.sum(matrix_3x3, axis=1)
other_col_sum_matrix

array([ 3, 12, 21])

In [56]:
matrix_3x3[0,:]

array([0, 1, 2])

In [57]:
matrix_3x3[:,0]

array([0, 3, 6])

In [58]:
len(matrix_3x3[:,0])

3

In [59]:
# Find the mean
col1_mean_matrix = (matrix_3x3[0,0] + matrix_3x3[1,0] + matrix_3x3[2,0]  ) / len(matrix_3x3[:,0])
col1_mean_matrix

#col_mean_matrix

3.0

In [60]:
# Find the mean
row1_mean_matrix = (matrix_3x3[0,1] + matrix_3x3[1,1] + matrix_3x3[2,1]  ) / len(matrix_3x3[:,1])
row1_mean_matrix

4.0

In [61]:
# Find the mean
col1_mean_matrix = (matrix_3x3[0,2] + matrix_3x3[1,2] + matrix_3x3[2,2]  ) / len(matrix_3x3[:,2])
col1_mean_matrix

5.0

In [62]:
# Find the mean
row_of_column_means = np.sum(matrix_3x3, axis=0 ) / len(matrix_3x3[:,0])
row_of_column_means

array([3., 4., 5.])

In [63]:
column_of_row_means = np.sum(matrix_3x3, axis=1 ) / len(matrix_3x3[0,:])
column_of_row_means

array([1., 4., 7.])

In [64]:
mean_matrix_3x3 = np.mean(matrix_3x3)
mean_matrix_3x3

4.0

In [65]:
#other_col1_mean_matrix[0]

In [66]:
matrix_3x3[0,:]

array([0, 1, 2])

## VARIANCE: Row 1

In [67]:
# Find all the (element - mean) in row 1

row1_element_minus_mean = matrix_3x3[0,:] - column_of_row_means[0]
row1_element_minus_mean

array([-1.,  0.,  1.])

In [68]:
# Find all the individual variances row 1

row1_individual_variances = (row1_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3[0,:]))
row1_individual_variances

array([0.33333333, 0.        , 0.33333333])

In [69]:
# Find the variance for row1 using the sumation

row1_variance = np.sum(row1_individual_variances)
row1_variance

0.6666666666666666

In [70]:
# Find the variance
# [(element - mean)^2] / num of elements

((matrix_3x3[0,0] - mean_matrix_3x3)**2) / len(matrix_3x3)


5.333333333333333

## VARIANCE: Row 2

In [71]:
# Find all the (element - mean) in row 2

row2_element_minus_mean = matrix_3x3[1,:] - column_of_row_means[1]
row2_element_minus_mean

array([-1.,  0.,  1.])

In [72]:
# Find all the individual variances row 2

row2_individual_variances = (row2_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3[1,:]))
row2_individual_variances

array([0.33333333, 0.        , 0.33333333])

In [73]:
# Find the variance for row2 using the sumation

row2_variance = np.sum(row2_individual_variances)
row2_variance

0.6666666666666666

## VARIANCE: Row 3

In [74]:
# Find all the (element - mean) in row 3

row3_element_minus_mean = matrix_3x3[2,:] - column_of_row_means[2]
row3_element_minus_mean

array([-1.,  0.,  1.])

In [75]:
# Find all the individual variances row 3

row3_individual_variances = (row3_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3[2,:]))
row3_individual_variances

array([0.33333333, 0.        , 0.33333333])

In [76]:
# Find the variance for row3 using the sumation

row3_variance = np.sum(row3_individual_variances)
row3_variance

0.6666666666666666

In [77]:
column_variances = [row1_variance, row2_variance, row3_variance]
column_variances

[0.6666666666666666, 0.6666666666666666, 0.6666666666666666]

## VARIANCE: Column 1

In [78]:
# Find all the (element - mean) in column 1

col1_element_minus_mean = matrix_3x3[:,0] - row_of_column_means[0]
col1_element_minus_mean

array([-3.,  0.,  3.])

In [79]:
np.count_nonzero(~np.isnan(matrix_3x3[:,0]))

3

In [80]:
# Find all the individual variances column 1

col1_individual_variances = (col1_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3[:,0]))
col1_individual_variances

array([3., 0., 3.])

In [81]:
# Find the variance for column 1 using the sumation

col1_variance = np.sum(col1_individual_variances)
col1_variance

6.0

## VARIANCE: Column 2

In [82]:
# Find all the (element - mean) in column 2

col2_element_minus_mean = matrix_3x3[:,1] - row_of_column_means[1]
col2_element_minus_mean

array([-3.,  0.,  3.])

In [83]:
np.count_nonzero(~np.isnan(matrix_3x3[:,1]))

3

In [84]:
# Find all the individual variances column 2

col2_individual_variances = (col2_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3[:,1]))
col2_individual_variances

array([3., 0., 3.])

In [85]:
# Find the variance for column 2 using the sumation

col2_variance = np.sum(col2_individual_variances)
col2_variance

6.0

## VARIANCE: Column 3

In [86]:
# Find all the (element - mean) in column 3

col3_element_minus_mean = matrix_3x3[:,2] - row_of_column_means[2]
col3_element_minus_mean

array([-3.,  0.,  3.])

In [87]:
# Find all the individual variances column 3

col3_individual_variances = (col3_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3[:,2]))
col3_individual_variances

array([3., 0., 3.])

In [88]:
# Find the variance for column 3 using the sumation

col3_variance = np.sum(col3_individual_variances)
col3_variance

6.0

In [89]:
row_variances = [col1_variance, col2_variance, col3_variance]

## VARIANCE: Entire Matrix

In [90]:
# Find all the (element - mean) in enitre matrix

matrix_element_minus_mean = matrix_3x3[:,:] - mean_matrix_3x3
matrix_element_minus_mean

array([[-4., -3., -2.],
       [-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

In [91]:
np.count_nonzero(~np.isnan(matrix_3x3))

9

In [92]:
# Find all the individual variances in enitre matrix

matrix_individual_variances = (matrix_element_minus_mean**2) / np.count_nonzero(~np.isnan(matrix_3x3))
matrix_individual_variances

array([[1.77777778, 1.        , 0.44444444],
       [0.11111111, 0.        , 0.11111111],
       [0.44444444, 1.        , 1.77777778]])

In [93]:
# Find the variance for the enitre matrix using the sumation

matrix_variance = np.sum(matrix_individual_variances)
matrix_variance

6.666666666666666

In [94]:
len(matrix_3x3[:,:])

3

In [95]:
variances = [row_variances, column_variances, matrix_variance]
variances

[[6.0, 6.0, 6.0],
 [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
 6.666666666666666]

# STANDARD DEVIATION

## Find Std Dev of Rows

In [101]:
row_variances

[6.0, 6.0, 6.0]

In [108]:
std_dev_row = np.sqrt(row_variances)
std_dev_row

array([2.44948974, 2.44948974, 2.44948974])

## Find Std Dev of Columns

In [109]:
column_variances

[0.6666666666666666, 0.6666666666666666, 0.6666666666666666]

In [110]:
std_dev_column = np.sqrt(column_variances)
std_dev_column

array([0.81649658, 0.81649658, 0.81649658])

## Find Std Dev of Entire Matrix

In [111]:
matrix_variance

6.666666666666666

In [112]:
std_dev_entire_matrix = np.sqrt(matrix_variance)
std_dev_entire_matrix

2.581988897471611

# Combine all Std Devs

In [128]:
std_devs = [std_dev_row, std_dev_column, std_dev_entire_matrix]
std_devs

[array([2.44948974, 2.44948974, 2.44948974]),
 array([0.81649658, 0.81649658, 0.81649658]),
 2.581988897471611]

# Convert all matrices and etc into a Dictionary

In [140]:
# Convert elements inside std_devs_row to a list
std_dev_row_list = std_dev_row.tolist()
std_dev_row_list

[2.449489742783178, 2.449489742783178, 2.449489742783178]

In [141]:
# Convert elements inside std_dev_row to a dictionary w/ an index starting at 1
std_dev_dict = dict(enumerate(std_dev_row.flatten(), 1))
std_dev_dict

{1: 2.449489742783178, 2: 2.449489742783178, 3: 2.449489742783178}

In [125]:
# dict({'standard deviation': [std_devs[0],std_devs[1],std_devs[2]]})
dict({'standard deviation': std_devs[0:3]})

{'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]),
  array([0.81649658, 0.81649658, 0.81649658]),
  2.581988897471611]}